//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKitchen.Store {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CartItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productIDField;
        
        private int amountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string productID {
            get {
                return this.productIDField;
            }
            set {
                if ((object.ReferenceEquals(this.productIDField, value) != true)) {
                    this.productIDField = value;
                    this.RaisePropertyChanged("productID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Store.StoreSoap")]
    public interface StoreSoap {
        
        // CODEGEN: Generating message contract since element name comments from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buy", ReplyAction="*")]
        IKitchen.Store.buyResponse buy(IKitchen.Store.buyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buy", ReplyAction="*")]
        System.Threading.Tasks.Task<IKitchen.Store.buyResponse> buyAsync(IKitchen.Store.buyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buy", Namespace="http://tempuri.org/", Order=0)]
        public IKitchen.Store.buyRequestBody Body;
        
        public buyRequest() {
        }
        
        public buyRequest(IKitchen.Store.buyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string comments;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime deliveryDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public IKitchen.Store.CartItem[] products;
        
        public buyRequestBody() {
        }
        
        public buyRequestBody(int userID, string comments, System.DateTime deliveryDate, IKitchen.Store.CartItem[] products) {
            this.userID = userID;
            this.comments = comments;
            this.deliveryDate = deliveryDate;
            this.products = products;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buyResponse", Namespace="http://tempuri.org/", Order=0)]
        public IKitchen.Store.buyResponseBody Body;
        
        public buyResponse() {
        }
        
        public buyResponse(IKitchen.Store.buyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int buyResult;
        
        public buyResponseBody() {
        }
        
        public buyResponseBody(int buyResult) {
            this.buyResult = buyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StoreSoapChannel : IKitchen.Store.StoreSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreSoapClient : System.ServiceModel.ClientBase<IKitchen.Store.StoreSoap>, IKitchen.Store.StoreSoap {
        
        public StoreSoapClient() {
        }
        
        public StoreSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IKitchen.Store.buyResponse IKitchen.Store.StoreSoap.buy(IKitchen.Store.buyRequest request) {
            return base.Channel.buy(request);
        }
        
        public int buy(int userID, string comments, System.DateTime deliveryDate, IKitchen.Store.CartItem[] products) {
            IKitchen.Store.buyRequest inValue = new IKitchen.Store.buyRequest();
            inValue.Body = new IKitchen.Store.buyRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.comments = comments;
            inValue.Body.deliveryDate = deliveryDate;
            inValue.Body.products = products;
            IKitchen.Store.buyResponse retVal = ((IKitchen.Store.StoreSoap)(this)).buy(inValue);
            return retVal.Body.buyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IKitchen.Store.buyResponse> IKitchen.Store.StoreSoap.buyAsync(IKitchen.Store.buyRequest request) {
            return base.Channel.buyAsync(request);
        }
        
        public System.Threading.Tasks.Task<IKitchen.Store.buyResponse> buyAsync(int userID, string comments, System.DateTime deliveryDate, IKitchen.Store.CartItem[] products) {
            IKitchen.Store.buyRequest inValue = new IKitchen.Store.buyRequest();
            inValue.Body = new IKitchen.Store.buyRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.comments = comments;
            inValue.Body.deliveryDate = deliveryDate;
            inValue.Body.products = products;
            return ((IKitchen.Store.StoreSoap)(this)).buyAsync(inValue);
        }
    }
}
